services:
  laravel:
    build:
      context: .
      dockerfile: laravel.dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www
    depends_on:
      - clickhouse
    networks:
      - appnet

  clickhouse:
    build: 
      context: .
      dockerfile: clickhouse.dockerfile
    image: clickhouse/clickhouse-server
    container_name: clickhouse_db
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./noaa:/data
      - ./scripts:/scripts
    networks:
      - appnet

  frontend_vue:
    image: node:22
    container_name: frontend_vue
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    networks:
      - appnet
    depends_on:
      - laravel

volumes:
  clickhouse_data:

networks:
  appnet:
    driver: bridge
